# library("bslib")
library("leaflet")
library("plotly")
library("shinycustomloader")
library("shinythemes")

navbarPage(
  "The impact of the 'Go to Travel' subsidy program on the increase in overall disease transmission in Japan during the 2020 COVID-19 pandemic",
  
  tabPanel("Data Description",
           fluidPage(
             # theme = shinytheme("paper"),
             theme = shinytheme("sandstone"),
             # theme = shinytheme("yeti"),
             # theme = bs_theme(bg = "#0b3d91", fg = "white", primary = "#FCC780",
             #                  base_font = font_google("Space Mono"),
             #                  code_font = font_google("Space Mono")),
             # titlePanel(""),
             mainPanel(
                strong("Go To Travel"),
                div("Go To Travel is a Japanese government subsidy program launched in 2020 to revive the pandemic-hit tourism industry.
                    The government offered Japanese residents reimbursement of part of their accommodation and travel costs,
                    and an additional part of the total travel cost in vouchers to be used for other travel expenses. The program
                    has received strong criticism from most Japanese prefectures, mainly due to concerns about the spread of the
                    pandemic and the inconsistency in the fight against COVID-19. The aim of this paper is to analyze
                    the relationship between data on COVID-19 cases in Japan and accommodation data from 2020."),
                br(),
                strong("COVID-19 data:"),
                tags$div("The original dataset was downloaded from the Japanese Ministry of Health, Labour and Welfare",
                       tags$a(href = "https://www.mhlw.go.jp/stf/covid-19/open-data.html", "website"),
                       "in 3 separate .csv files."),
                tags$div("After combining into one file, the dataset consists of 5 columns and 16,027 rows of daily
                         data on COVID-19 infections, deaths and severe cases on Japanese territory on a prefecture level
                         since January 26th 2020 until December 31st 2020."),
                tags$div("The columns include:",
                         tags$ul(tags$li(tags$code("Date")),
                                 tags$li(tags$code("Prefecture")),
                                 tags$li(tags$code("NewlyConfirmedCases"),"- Number of newly confirmed COVID-19 cases in each prefecture,"),
                                 tags$li(tags$code("NumberOfDeaths"),"- Number of COVID-19 related deaths in each prefecture,"),
                                 tags$li(tags$code("SevereCases"),"- Number of severe COVID-19 cases in each prefecture."))),
                br(),
                strong("Accommodation data:"),
                tags$div("The original dataset was downloaded from the Japanese Ministry of Land, Infrastructure, Transport and Tourism",
                         tags$a(href = "https://www.mlit.go.jp/kankocho/siryou/toukei/shukuhakutoukei.html", "website"),
                         "in an .xlsx format."),
                tags$div("After data wrangling, it consists of 44 columns and 564 rows of monthly accommodation
                         data on a prefecture level from 2020."),
                tags$div("The columns include:",
                         tags$ul(
                                 tags$li(tags$code("Date")),
                                 tags$li(tags$code("Prefecture")),
                                 tags$li(tags$code("Guests_Total"), "- Total number of guests in each prefecture,"),
                                 tags$li(tags$code("Guests_Prefecture"), "- Total number of guests from the prefecture,"),
                                 tags$li(tags$code("Guests_OutsidePrefecture"), "- Total number of guests from outside of the prefecture,"),
                                 tags$li(tags$code("Type_Ryokan"), "- Total number of guests staying in a ryokan,"),
                                 tags$li(tags$code("Type_Resort"), "- Total number of guests staying in a resort hotel,"),
                                 tags$li(tags$code("Type_Business"), "- Total number of guests staying in a business hotel,"),
                                 tags$li(tags$code("Type_City"), "- Total number of guests staying in a city hotel,"),
                                 tags$li(tags$code("Type_Simple"), "- Total number of guests staying in a simple lodging facility (simple lodging refers to
                                         facilities that provide rooms for common usage such as youth hostels, capsule hotels, guest houses
                                         or mountain shacks),"),
                                 tags$li(tags$code("Type_CompaniesGroups"), "- Total number of guests staying in an accommodation for companies and groups,"),
                                 tags$li(tags$code("Pref_Ryokan"), "- Total number of guests from the prefecture staying in a ryokan,"),
                                 tags$li(tags$code("Out_Ryokan"), "- Total number of guests from outside of the prefecture staying in a ryokan,"),
                                 tags$li(tags$code("Pref_Resort"), "- Total number of guests from the prefecture staying in a resort hotel,"),
                                 tags$li(tags$code("Out_Resort"), "- Total number of guests from outside of the prefecture staying in a resort hotel,"),
                                 tags$li(tags$code("Pref_Business"), "- Total number of guests from the prefecture staying in a resort hotel,"),
                                 tags$li(tags$code("Out_Business"), "- Total number of guests from outside of the prefecture staying in a resort hotel,"),
                                 tags$li(tags$code("Pref_City"), "- Total number of guests from the prefecture staying in a city hotel,"),
                                 tags$li(tags$code("Out_City"), "- Total number of guests from outside of the prefecture staying in a city hotel,"),
                                 tags$li(tags$code("Pref_Simple"), "- Total number of guests from the prefecture staying in a simple lodging facility,"),
                                 tags$li(tags$code("Out_Simple"), "- Total number of guests from outside of the prefecture staying in a simple lodging facility,"),
                                 tags$li(tags$code("Pref_CompaniesGroups"), "- Total number of guests from the prefecture staying in an accommodation for companies and groups,"),
                                 tags$li(tags$code("Out_CompaniesGroups"), "- Total number of guests from outside of the prefecture staying in an accommodation for companies and groups,"),
                                 tags$li(tags$code("Occupancy_Rate"), "- Occupancy rate in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Tourists"), "- Tourist occupancy rate in each prefecture,"),
                                 tags$li(tags$code("Occupancy_NonTourists"), "- Non-tourist occupancy rate in each prefecture,"),
                                 tags$li(tags$code("Occupancy_0to9"), "- Occupancy rate of accommodation with 0-9 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Tourists_0to9"), "- Tourist occupancy rate of accommodation with 0-9 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_NonTourists_0to9"), "- Non-tourist occupancy rate of accommodation with 0-9 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_10to19"), "- Occupancy rate of accommodation with 10-19 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Tourists_10to19"), "- Tourist occupancy rate of accommodation with 10-19 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_NonTourists_10to19"), "- Non-tourist occupancy rate of accommodation with 10-19 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_30to99"), "- Occupancy rate of accommodation with 30-99 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Tourists_30to99"), "- Tourist occupancy rate of accommodation with 30-99 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_NonTourists_30to99"), "- Non-tourist occupancy rate of accommodation with 30-99 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_over100"), "- Occupancy rate of accommodation with over 100 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Tourists_over100"), "- Tourist occupancy rate of accommodation with over 100 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_NonTourists_over100"), "- Non-tourist occupancy rate of accommodation with over 100 employees in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Ryokan"), "- Occupancy rate of ryokans in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Resort"), "- Occupancy rate of resort hotels in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Business"), "- Occupancy rate of business hotels in each prefecture,"),
                                 tags$li(tags$code("Occupancy_City"), "- Occupancy rate of city hotels in each prefecture,"),
                                 tags$li(tags$code("Occupancy_Simple"), "- Occupancy rate of simple lodging facilities in each prefecture,"),
                                 tags$li(tags$code("Occupancy_CompaniesGroups"), "- Occupancy rate of accommodation for companies and groups in each prefecture.")))
           )),
           hr(),
           tags$em("Stefania Siorek, 2022")),
  
  tabPanel("COVID-19 Infections",
           fluidPage(
             div(
               selectInput("selected_prefecture",
                           "Selected prefecture:",
                           choices = c("Aichi", "Akita", "Aomori", "Chiba",
                                       "Ehime", "Fukui", "Fukuoka", "Fukushima",
                                       "Gifu", "Gunma", "Hiroshima", "Hokkaido",
                                       "Hyogo", "Ibaraki", "Ishikawa", "Iwate",
                                       "Kagawa", "Kagoshima", "Kanagawa", "Kochi",
                                       "Kumamoto", "Kyoto", "Mie", "Miyagi",
                                       "Miyazaki", "Nagano", "Nagasaki", "Nara",
                                       "Niigata", "Oita", "Okayama", "Okinawa",
                                       "Osaka", "Saga", "Saitama", "Shiga",
                                       "Shimane", "Shizuoka", "Tochigi", "Tokushima",
                                       "Tokyo", "Tottori", "Toyama", "Wakayama",
                                       "Yamagata", "Yamaguchi", "Yamanashi"
                           )),
               selectInput("selected_column_1",
                           "Selected data:",
                           choices = c("Number of New COVID-19 Cases" = "NewlyConfirmedCases",
                                       "Number of COVID-19 Related Deaths" = "NumberOfDeaths",
                                       "Number of Severe COVID-19 Cases" = "SevereCases")),
               style = "position:relative;z-index:10000;"
             ),
             #actionButton("update_chart", label = "Update chart", width = "100%"),
             withLoader(plotlyOutput("covid_plot"), type = "html", loader = "loader4")
           ),
           hr(),
           tags$em("Stefania Siorek, 2022")),
  
  tabPanel("Accommodation",
           fluidPage(
             div(
               selectInput("selected_prefecture_2",
                           "Selected prefecture:",
                           choices = c("Aichi", "Akita", "Aomori", "Chiba",
                                       "Ehime", "Fukui", "Fukuoka", "Fukushima",
                                       "Gifu", "Gunma", "Hiroshima", "Hokkaido",
                                       "Hyogo", "Ibaraki", "Ishikawa", "Iwate",
                                       "Kagawa", "Kagoshima", "Kanagawa", "Kochi",
                                       "Kumamoto", "Kyoto", "Mie", "Miyagi",
                                       "Miyazaki", "Nagano", "Nagasaki", "Nara",
                                       "Niigata", "Oita", "Okayama", "Okinawa",
                                       "Osaka", "Saga", "Saitama", "Shiga",
                                       "Shimane", "Shizuoka", "Tochigi", "Tokushima",
                                       "Tokyo", "Tottori", "Toyama", "Wakayama",
                                       "Yamagata", "Yamaguchi", "Yamanashi"
                           )),
               selectInput("selected_column_2",
                           "Selected data:",
                           choices = c("Total Number of Guests" = "Guests_Total",
                                       "Guests From the Prefecture" = "Guests_Prefecture",
                                       "Guests From Outside of the Prefecture" = "Guests_OutsidePrefecture",
                                       "Accommodation Type: Ryokan" = "Type_Ryokan",
                                       "Accommodation Type: Resort Hotel" = "Type_Resort",
                                       "Accommodation Type: Business Hotel" = "Type_Business",
                                       "Accommodation Type: City Hotel" = "Type_City",
                                       "Accommodation Type: Simple Lodging Facility" = "Type_Simple",
                                       "Accommodation Type: Accommodation for Companies and Groups" = "Type_CompaniesGroups",
                                       "Guests from the Prefecture: Ryokan" = "Pref_Ryokan",
                                       "Guests from the Prefecture: Resort Hotel" = "Pref_Resort",
                                       "Guests from the Prefecture: Business Hotel" = "Pref_Business",
                                       "Guests from the Prefecture: City Hotel" = "Pref_City",
                                       "Guests from the Prefecture: Simple Lodging Facility" = "Pref_Simple",
                                       "Guests from the Prefecture: Accommodation for Companies and Groups" = "Pref_CompaniesGroups",
                                       "Guests from Outside of the Prefecture: Ryokan" = "Out_Ryokan",
                                       "Guests from Outside of the Prefecture: Resort Hotel" = "Out_Resort",
                                       "Guests from Outside of the Prefecture: Business Hotel" = "Out_Business",
                                       "Guests from Outside of the Prefecture: City Hotel" = "Out_City",
                                       "Guests from Outside of the Prefecture: Simple Lodging Facility" = "Out_Simple",
                                       "Guests from Outside of the Prefecture: Accommodation for Companies and Groups" = "Out_CompaniesGroups",
                                       "Occupancy Rate" = "Occupancy_Rate",
                                       "Tourist Occupancy Rate" = "Occupancy_Tourists",
                                       "Non-tourist Occupancy Rate" = "Occupancy_NonTourists",
                                       "Occupancy Rate: Accommodation with 0-9 employees" = "Occupancy_0to9",
                                       "Tourist Occupancy Rate: Accommodation with 0-9 employees" = "Occupancy_Tourists_0to9",
                                       "Non-tourist Occupancy Rate: Accommodation with 0-9 employees" = "Occupancy_NonTourists_0to9",
                                       "Occupancy Rate: Accommodation with 10-19 employees" = "Occupancy_10to19",
                                       "Tourist Occupancy Rate: Accommodation with 10-19 employees" = "Occupancy_Tourists_10to19",
                                       "Non-tourist Occupancy Rate: Accommodation with 10-19 employees" = "Occupancy_NonTourists_10to19",
                                       "Occupancy Rate: Accommodation with 30-99 employees" = "Occupancy_30to99",
                                       "Tourist Occupancy Rate: Accommodation with 30-99 employees" = "Occupancy_Tourists_30to99",
                                       "Non-tourist Occupancy Rate: Accommodation with 30-99 employees" = "Occupancy_NonTourists_30to99",
                                       "Occupancy Rate: Accommodation with over 100 employees" = "Occupancy_over100",
                                       "Tourist Occupancy Rate: Accommodation with over 100 employees" = "Occupancy_Tourists_over100",
                                       "Non-tourist Occupancy Rate: Accommodation with over 100 employees" = "Occupancy_NonTourists_over100",
                                       "Occupancy Rate: Ryokan" = "Occupancy_Ryokan",
                                       "Occupancy Rate: Resort Hotel" = "Occupancy_Resort",
                                       "Occupancy Rate: Business Hotel" = "Occupancy_Business",
                                       "Occupancy Rate: City Hotel" = "Occupancy_City",
                                       "Occupancy Rate: Simple Lodging Facility" = "Occupancy_Simple",
                                       "Occupancy Rate: Accommodation for Companies and Groups" = "Occupancy_CompaniesGroups"
                           )),
               style = "position:relative;z-index:10000;"
             ),
             #actionButton("update_chart_2", label = "Update chart", width = "100%"),
             withLoader(plotlyOutput("shukuhaku_plot"), type = "html", loader = "loader4")
           ),
           hr(),
           tags$em("Stefania Siorek, 2022")),

  tabPanel("Comparison",
           fluidPage(
             div(
               selectInput("selected_prefecture_5",
                           "Selected prefecture:",
                           choices = c("Aichi", "Akita", "Aomori", "Chiba",
                                       "Ehime", "Fukui", "Fukuoka", "Fukushima",
                                       "Gifu", "Gunma", "Hiroshima", "Hokkaido",
                                       "Hyogo", "Ibaraki", "Ishikawa", "Iwate",
                                       "Kagawa", "Kagoshima", "Kanagawa", "Kochi",
                                       "Kumamoto", "Kyoto", "Mie", "Miyagi",
                                       "Miyazaki", "Nagano", "Nagasaki", "Nara",
                                       "Niigata", "Oita", "Okayama", "Okinawa",
                                       "Osaka", "Saga", "Saitama", "Shiga",
                                       "Shimane", "Shizuoka", "Tochigi", "Tokushima",
                                       "Tokyo", "Tottori", "Toyama", "Wakayama",
                                       "Yamagata", "Yamaguchi", "Yamanashi")),
               style = "position:relative;z-index:10000;"
             ),
             withLoader(plotOutput("comparison_plot"), type = "html", loader = "loader4")
           ),
           hr(),
           tags$em("Stefania Siorek, 2022")),
  
  tabPanel("Comparison Maps",
           fluidPage(
             div(
               selectInput("selected_date_maps",
                           "Selected date:",
                           choices = c("January 2020" = "2020-01-01",
                                       "February 2020" = "2020-02-01",
                                       "March 2020" = "2020-03-01",
                                       "April 2020" = "2020-04-01",
                                       "May 2020" = "2020-05-01",
                                       "June 2020" = "2020-06-01",
                                       "July 2020" = "2020-07-01",
                                       "August 2020" = "2020-08-01",
                                       "September 2020" = "2020-09-01",
                                       "October 2020" = "2020-10-01",
                                       "November 2020" = "2020-11-01",
                                       "December 2020" = "2020-12-01"
                           )),
               style = "position:relative;z-index:10000;"
             ),
             span(textOutput("textmaps"), style = "color:red"),
             leafletOutput("maps"),
             span(textOutput("textmapsguests"), style = "color:red"),
             leafletOutput("mapsguests")
           ),
           hr(),
           tags$em("Stefania Siorek, 2022")),
  
  tabPanel("COVID-19 Data",
           fluidPage(
             div(
               selectInput("selected_prefecture_3",
                           "Selected prefecture:",
                           choices = c("Aichi", "Akita", "Aomori", "Chiba",
                                       "Ehime", "Fukui", "Fukuoka", "Fukushima",
                                       "Gifu", "Gunma", "Hiroshima", "Hokkaido",
                                       "Hyogo", "Ibaraki", "Ishikawa", "Iwate",
                                       "Kagawa", "Kagoshima", "Kanagawa", "Kochi",
                                       "Kumamoto", "Kyoto", "Mie", "Miyagi",
                                       "Miyazaki", "Nagano", "Nagasaki", "Nara",
                                       "Niigata", "Oita", "Okayama", "Okinawa",
                                       "Osaka", "Saga", "Saitama", "Shiga",
                                       "Shimane", "Shizuoka", "Tochigi", "Tokushima",
                                       "Tokyo", "Tottori", "Toyama", "Wakayama",
                                       "Yamagata", "Yamaguchi", "Yamanashi"
                           )),
               DT::DTOutput("covid_data")
             )),
           hr(),
           tags$em("Stefania Siorek, 2022")),
  
  tabPanel("Accommodation Data",
           fluidPage(
             div(
               selectInput("selected_prefecture_4",
                           "Selected prefecture:",
                           choices = c("Aichi", "Akita", "Aomori", "Chiba",
                                       "Ehime", "Fukui", "Fukuoka", "Fukushima",
                                       "Gifu", "Gunma", "Hiroshima", "Hokkaido",
                                       "Hyogo", "Ibaraki", "Ishikawa", "Iwate",
                                       "Kagawa", "Kagoshima", "Kanagawa", "Kochi",
                                       "Kumamoto", "Kyoto", "Mie", "Miyagi",
                                       "Miyazaki", "Nagano", "Nagasaki", "Nara",
                                       "Niigata", "Oita", "Okayama", "Okinawa",
                                       "Osaka", "Saga", "Saitama", "Shiga",
                                       "Shimane", "Shizuoka", "Tochigi", "Tokushima",
                                       "Tokyo", "Tottori", "Toyama", "Wakayama",
                                       "Yamagata", "Yamaguchi", "Yamanashi"
                           )),
                selectInput("selected_column2",
                            "Selected data:",
                            choices = c("Total Guests",
                                        "Guests From the Prefecture",
                                        "Guests From Outside of the Prefecture",
                                        "Accommodation Type: Ryokan",
                                        "Accommodation Type: Resort Hotel",
                                        "Accommodation Type: Business Hotel",
                                        "Accommodation Type: City Hotel",
                                        "Accommodation Type: Simple Lodging",
                                        "Accommodation Type: Accommodation for Companies and Groups",
                                        "Guests from the Prefecture: Ryokan",
                                        "Guests from the Prefecture: Resort Hotel",
                                        "Guests from the Prefecture: Business Hotel",
                                        "Guests from the Prefecture: City Hotel",
                                        "Guests from the Prefecture: Simple Lodging",
                                        "Guests from the Prefecture: Accommodation for Companies and Groups",
                                        "Guests from Outside of the Prefecture: Ryokan",
                                        "Guests from Outside of the Prefecture: Resort Hotel",
                                        "Guests from Outside of the Prefecture: Business Hotel",
                                        "Guests from Outside of the Prefecture: City Hotel",
                                        "Guests from Outside of the Prefecture: Simple Lodging",
                                        "Guests from Outside of the Prefecture: Accommodation for Companies and Groups",
                                        "Occupancy Rate",
                                        "Tourist Occupancy Rate",
                                        "Non Tourist Occupancy Rate",
                                        "Occupancy Rate: Accommodation with 0-9 employees",
                                        "Tourist Occupancy Rate: Accommodation with 0-9 employees",
                                        "Non Tourist Occupancy Rate: Accommodation with 0-9 employees",
                                        "Occupancy Rate: Accommodation with 10-19 employees",
                                        "Tourist Occupancy Rate: Accommodation with 10-19 employees",
                                        "Non Tourist Occupancy Rate: Accommodation with 10-19 employees",
                                        "Occupancy Rate: Accommodation with 30-99 employees",
                                        "Tourist Occupancy Rate: Accommodation with 30-99 employees",
                                        "Non Tourist Occupancy Rate: Accommodation with 30-99 employees",
                                        "Occupancy Rate: Accommodation with over 100 employees",
                                        "Tourist Occupancy Rate: Accommodation with over 100 employees",
                                        "Non Tourist Occupancy Rate: Accommodation with over 100 employees",
                                        "Occupancy Rate: Ryokan",
                                        "Occupancy Rate: Resort Hotel",
                                        "Occupancy Rate: Business Hotel",
                                        "Occupancy Rate: City Hotel",
                                        "Occupancy Rate: Simple Lodging",
                                        "Occupancy Rate: Accommodation for Companies and Groups"
                            )
                ),
               DT::DTOutput("shukuhaku_data")
             )),
           hr(),
           tags$em("Stefania Siorek, 2022")),
  
  collapsible = TRUE
)